FROM openjdk:17-alpine
MAINTAINER Ernesto
COPY target/SubscriptionService-0.0.1-SNAPSHOT.jar SubscriptionService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/SubscriptionService-0.0.1-SNAPSHOT.jar"]