FROM openjdk:17-alpine
MAINTAINER Ernesto
COPY target/KafkaConsumerService-0.0.1-SNAPSHOT.jar KafkaConsumerService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/KafkaConsumerService-0.0.1-SNAPSHOT.jar"]